name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.2'
            moodle-branch: 'MOODLE_405_STABLE'
            database: mysqli

    steps:
      - name: Checkout plugin
        uses: actions/checkout@v4
        with:
          path: plugin

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, xml, curl, zip, gd, mysqli
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install moodle-plugin-ci
        run: |
          composer create-project -n moodlehq/moodle-plugin-ci ci ^4
          echo "$(pwd)/ci/bin" >> $GITHUB_PATH
          echo "$(pwd)/ci/vendor/bin" >> $GITHUB_PATH

      - name: Install Moodle
        run: moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: PHPCS
        run: moodle-plugin-ci phpcs --max-warnings 0

      - name: Validate
        run: moodle-plugin-ci validate

      - name: Mustache
        run: moodle-plugin-ci mustache

      - name: Grunt
        run: moodle-plugin-ci grunt